import { Metadata } from 'next';
import Link from 'next/link';
import { FileText, AlertTriangle, CheckCircle2 } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service | Juan Isaac',
  description: 'Terms of service for Juan Isaac portfolio website',
};

export default function TermsPage() {
  const lastUpdated = 'January 6, 2025';

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b">
        <div className="container mx-auto px-4 py-6">
          <Link
            href="/"
            className="text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            ← Back to Portfolio
          </Link>
        </div>
      </header>

      {/* Main Content */}
      <section className="container mx-auto px-4 py-16">
        <div className="mx-auto max-w-3xl">
          <div className="mb-8">
            <h1 className="mb-4 text-4xl font-bold tracking-tight">Terms of Service</h1>
            <p className="text-muted-foreground">
              Last updated: {lastUpdated}
            </p>
          </div>

          <div className="prose prose-gray dark:prose-invert max-w-none">
            {/* Introduction */}
            <section className="mb-8">
              <div className="mb-4 flex items-center gap-2">
                <FileText className="h-6 w-6 text-primary" />
                <h2 className="text-2xl font-semibold">Agreement to Terms</h2>
              </div>
              <p className="text-muted-foreground">
                By accessing this portfolio website, you agree to be bound by these Terms of Service and
                our Privacy Policy. If you disagree with any part of the terms, you may not access the
                service.
              </p>
            </section>

            {/* Use of Service */}
            <section className="mb-8">
              <div className="mb-4 flex items-center gap-2">
                <CheckCircle2 className="h-6 w-6 text-primary" />
                <h2 className="text-2xl font-semibold">Acceptable Use</h2>
              </div>
              <div className="space-y-3 text-muted-foreground">
                <p>You agree to use this website only for lawful purposes. You agree not to:</p>
                <ul className="space-y-2">
                  <li>• Use the site in any way that violates applicable laws or regulations</li>
                  <li>• Attempt to gain unauthorized access to any portion of the site</li>
                  <li>
                    • Engage in any automated data collection without express written permission
                  </li>
                  <li>• Transmit any malicious code or interfere with the proper functioning of the site</li>
                  <li>• Use the AI chatbot for purposes other than portfolio-related inquiries</li>
                </ul>
              </div>
            </section>

            {/* Intellectual Property */}
            <section className="mb-8">
              <h2 className="mb-4 text-2xl font-semibold">Intellectual Property</h2>
              <div className="space-y-3 text-muted-foreground">
                <p>
                  All content on this website, including text, graphics, logos, and code, is the property
                  of Juan Isaac or used with permission. You may not reproduce, distribute, or create
                  derivative works without explicit permission.
                </p>
                <p>
                  Project descriptions and case studies represent work performed by Juan Isaac. Actual
                  project code and implementations remain subject to their respective licenses and
                  agreements.
                </p>
              </div>
            </section>

            {/* AI Chatbot Usage */}
            <section className="mb-8">
              <h2 className="mb-4 text-2xl font-semibold">AI Chatbot Terms</h2>
              <div className="space-y-3 text-muted-foreground">
                <p>The AI-powered chatbot on this site is provided for informational purposes only:</p>
                <ul className="space-y-2">
                  <li>
                    • Responses are generated by AI and may not always be accurate or complete
                  </li>
                  <li>• The chatbot is designed to answer portfolio-related questions only</li>
                  <li>• Conversations are not permanently stored or linked to your identity</li>
                  <li>
                    • Do not share sensitive or confidential information through the chatbot
                  </li>
                  <li>• The chatbot does not constitute professional advice of any kind</li>
                </ul>
              </div>
            </section>

            {/* Disclaimer */}
            <section className="mb-8 rounded-lg border-l-4 border-yellow-500 bg-yellow-50 dark:bg-yellow-950/20 p-6">
              <div className="mb-3 flex items-center gap-2">
                <AlertTriangle className="h-6 w-6 text-yellow-600 dark:text-yellow-500" />
                <h2 className="text-xl font-semibold text-yellow-900 dark:text-yellow-100">Disclaimer</h2>
              </div>
              <p className="text-sm text-yellow-900 dark:text-yellow-100">
                This website and its content are provided "as is" without warranties of any kind, either
                express or implied. Juan Isaac makes no warranties about the accuracy, reliability, or
                completeness of the information provided. Use of this site is at your own risk.
              </p>
            </section>

            {/* Limitation of Liability */}
            <section className="mb-8">
              <h2 className="mb-4 text-2xl font-semibold">Limitation of Liability</h2>
              <p className="text-muted-foreground">
                To the maximum extent permitted by law, Juan Isaac shall not be liable for any indirect,
                incidental, special, consequential, or punitive damages resulting from your use of or
                inability to use the site.
              </p>
            </section>

            {/* Educational Projects Safety */}
            <section className="mb-8 rounded-lg border-l-4 border-primary bg-accent/50 p-6">
              <h2 className="mb-3 text-xl font-semibold">Educational Projects & Child Safety</h2>
              <p className="text-sm text-muted-foreground">
                This portfolio references educational technology projects that serve minors (such as
                AllowMe.ai). These projects operate under separate terms of service with:
              </p>
              <ul className="mt-3 space-y-1 text-sm text-muted-foreground">
                <li>• Parental consent requirements</li>
                <li>• COPPA and FERPA compliance</li>
                <li>• Data minimization practices</li>
                <li>• Secure payment guardrails and parental controls</li>
              </ul>
              <p className="mt-3 text-sm text-muted-foreground">
                This portfolio website itself does not collect information from children under 13.
              </p>
            </section>

            {/* External Links */}
            <section className="mb-8">
              <h2 className="mb-4 text-2xl font-semibold">External Links</h2>
              <p className="text-muted-foreground">
                This site contains links to external websites and project repositories. Juan Isaac is not
                responsible for the content or privacy practices of these external sites.
              </p>
            </section>

            {/* Changes to Terms */}
            <section className="mb-8">
              <h2 className="mb-4 text-2xl font-semibold">Changes to Terms</h2>
              <p className="text-muted-foreground">
                We reserve the right to modify these terms at any time. Changes will be posted on this
                page with an updated "Last updated" date. Continued use of the site after changes
                constitutes acceptance of the new terms.
              </p>
            </section>

            {/* Governing Law */}
            <section className="mb-8">
              <h2 className="mb-4 text-2xl font-semibold">Governing Law</h2>
              <p className="text-muted-foreground">
                These terms shall be governed by and construed in accordance with the laws of the State of
                New York, United States, without regard to its conflict of law provisions.
              </p>
            </section>

            {/* Contact */}
            <section>
              <h2 className="mb-4 text-2xl font-semibold">Contact Information</h2>
              <p className="text-muted-foreground">
                If you have questions about these Terms of Service, please contact us at:{' '}
                <a href="mailto:juandejesusisaac@gmail.com" className="text-primary hover:underline">
                  juandejesusisaac@gmail.com
                </a>
              </p>
            </section>
          </div>
        </div>
      </section>
    </div>
  );
}

